medicineshop/feedback/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

app_name='feedback'

urlpatterns = [

    path('',views.ck,name="feedbacks"),
    path('gvfdk/',views.gvfdk,name="feedbacks"),
    
]

medicineshop/medicineshop/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from src import views as V

app_name='med'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('src/', include('src.urls')),
    path('feedback/', include('feedback.urls')),
    path('', V.home),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

medicineshop/src/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

app_name='src'

urlpatterns = [
    path('',views.home),

    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
   
    url(r'^custform/', views.custform, name="custform"),
    url(r'^custforminsert/', views.custforminsert, name="custforminsert"),
    url(r'^custformupdate(?P<foo>[0-9]+)/', views.custformupdate, name="custformupdate"),
    url(r'^custformview(?P<foo>[0-9]+)/', views.custformview, name="custformview"),
    url(r'^custformdelete(?P<foo>[0-9]+)/', views.custformdelete, name="custformdelete"),
    url(r'^custtable/', views.custtable, name='custtable'),

    url(r'^medform/', views.medform, name="medform"),
    url(r'^medforminsert/', views.medforminsert, name="medforminsert"),
    url(r'^medformupdate(?P<foo>[0-9]+)/', views.medformupdate, name="medformupdate"),
    url(r'^medformview(?P<foo>[0-9]+)/', views.medformview, name="medformview"),
    url(r'^medformdelete(?P<foo>[0-9]+)/', views.medformdelete, name="medformdelete"),
    url(r'^medtable/', views.medtable, name='medtable'),

    url(r'^ordform/', views.ordform, name="ordform"),
    url(r'^ordforminsert/', views.ordforminsert, name="ordforminsert"),
    url(r'ordformupdate(?P<foo>[0-9]+)/', views.ordformupdate, name="ordformupdate"),
    url(r'^ordformview(?P<foo>[0-9]+)/', views.ordformview, name="ordformview"),
    url(r'^ordformdelete(?P<foo>[0-9]+)/', views.ordformdelete, name="ordformdelete"),
    url(r'^ordtable/', views.ordtable, name='ordtable'),

    url(r'^insform/', views.insform, name="insform"),
    url(r'^insforminsert/', views.insforminsert, name="insforminsert"),
    url(r'^insformupdate(?P<foo>[0-9]+)/', views.insformupdate, name="insformupdate"),
    url(r'^insformview(?P<foo>[0-9]+)/', views.insformview, name="insformview"),
    url(r'^insformdelete(?P<foo>[0-9]+)/', views.insformdelete, name="insformdelete"),
    url(r'^instable/', views.instable, name='instable'),

    url(r'^cart/', views.cart, name="cart"),
    url(r'^pres/', views.pres, name="pres"),
    url(r'^check/', views.check, name="check"),
    
    url(r'^viewpurchase/', views.viewpurchase, name="viewpurchase"),

]

medicineshop/feedback/models.py
from django.db import models

# Create your models here.

class feed(models.Model):
    c_id = models.CharField(max_length=30)
    feedbacks=models.CharField(max_length=200)

    def __str__(self):
        return self.c_id

medicineshop/feedback/views.py
from django.shortcuts import render
from .models import feed

# Create your views here.

def ck(request):
    f=feed()
    dict = {'feed': f}
    return render(request, 'feedback/fdk.html',dict)

def gvfdk(request):
    f=feed()
    f.c_id = request.POST['c_id']
    f.feedbacks = request.POST['feedbacks']
    f.save(using="feedback")
    
    return render(request, 'feedback/tnx.html')

medicineshop/feedback/templates/feedback/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!--<link rel="icon" href="{% static 'img/RVCE_New_Logo.jpeg' %}" type="image/jpeg" sizes="16x16">-->

  {% block title %}<title>Medical-Shop</title>{% endblock %}

  {% block head %}
  {% endblock %}
  <nav>
    <ul>
        {% if user.is_authenticated %}
        <li>
            <form class="logout-link" action="{%url 'src:logout'%}" method="post">
             {% csrf_token %}
                <button type="submit">logout</button>
            </form>
        </li>
        {% else %}
        <li><a href="{% url 'src:login' %}">Login</a></li>
        <li><a href="{% url 'src:signup' %}">Signup</a></li>
        {% endif %}
    </ul>
</nav>


</head>
<body>

  {% block content %}
  {% endblock %}


 <!-- {% block js %}
    <script src="{% static 'js/main.js' %}"></script>
  {% endblock %}-->

</body>
</html>

medicineshop/feedback/templates/feedback/fdk.html
{% extends 'feedback/base.html' %}
{% load static %}

    {% block content %}
<head>
    <title>feedback</title>
    <style>
        body {
          background-image: url('../../../static/medicineshop/images/feedback1.jpg');
          background-repeat: no-repeat;
          background-attachment: fixed;  
          background-size: cover;
        }
        </style>
        </head>
        <style>
            h2{
            font-family:sans-serif;
            text-transform:uppercase;
            letter-spacing:6pt;
            font: size 2em;
            color:black;
            line-height:1.6em;
            text-align: center;
          }
          
          </style>
    
</head>

    
{% if user.is_authenticated %}
<div class="container">
    <div class="col-md-2"></div>
    <div class="panel panel-default col-md-8 jumcust2">
        
        <div class="panel-body">
                <form action="/feedback/gvfdk/" method="post">
                    {% csrf_token %}
                    <div class="row padtop15">
                        <div class="col-md-3 padtop5">
                            <label for="c_id" class="form-control-label">ID:</label>
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" name="c_id" class="form-control" id="c_id" placeholder="ID"
                                   value="{{ fdk.c_id }}" required/>
                        </div>
                        
                    </div>
                    <div class="row padtop15">
                        <div class="col-md-3 padtop5">
                            <label for="feedbacks" class="form-control-label">feedback:</label>
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" name="feedbacks" class="form-control" id="feedbacks" placeholder="feedbacks"
                                   value="{{ fdk.feedbacks }}" required/>
                        </div>
                       
                    </div>
                  
                            <button type="submit" class="btn btn-default"><a href="/src/">Cancel</a></button>
                        </div>
                        <div class="col-md-2 padtop15">
                            <button type="submit" class="btn btn-primary">
                                submit</button>
                        </div>
                        
                    </div>
                </form>
           
{% else %}
<h1> LOGIN TO ACCESS</h1>
{% endif %}

{% endblock %}

medicineshop/feedback/templates/feedback/tnx.html
{% extends 'feedback/base.html' %}
{% load static %}

    {% block content %}
<head>
    <style>
        body {
          background-image: url('../../../static/medicineshop/images/feedback1.jpg');
          background-repeat: no-repeat;
          background-attachment: fixed;  
          background-size: cover;
        }
        </style>
        </head>
        <style>
            h2{
            font-family:sans-serif;
            text-transform:uppercase;
            letter-spacing:6pt;
            font: size 2em;
            color:black;
            line-height:1.6em;
            text-align: center;
          }
          
          </style>
    <title>THANK YOU</title>
</head>

    {% if user.is_authenticated %}

<h2>THANK YOU FOR THE FEEDBACK</h2>


{% else %}
<h1> LOGIN TO ACCESS</h1>
{% endif %}


{% endblock %}